# This is the main config file, obviously!

# icon        - The represented block in the chest menu
# access      - Player XP Level Required
# removelevel - Will accessing remove the XP levels?
# lockout     - The amount of time before a player can access it again
# size        - The size of the container (multiples of 9)
# enabled     - Wether or not the chest is enabled on startup

# Donation Chest
dchest:
  icon: jukebox
  access: 0
  removelevel: false
  lockout: 0
# clean    - When will the donation chest remove all items in seconds
# warning  - When will the clean warning appear (minus the clean amount)
# critical - When will the critical warning appear (minus the clean amount)
  clean: 10800
  warning: 900
  critical: 60
  random:
# timer      - In minutes when to grab a random number
# chance     - If the random number hits the half of the total it will randomise
# itemsecond - How many seconds in between a player can grab another item
# countdown  - How long does the randomise restriction last in seconds
    timer: 300
    chance: 100
    itemsecond: 3
    countdown: 30
  size: 54
  enabled: true

# Enchantment Chest
echest: workbench
  icon:
  access: 5
  removelevel: true
  lockout: 120
# unsafe - Should unsafe enchants be allowed on items? Careful with this!
  unsafe: false
  enabled: true

# Hold Chest
hchest:
  icon: chest
  access: 5
  removelevel: false
  lockout: 0
# keepondeath - Negates the hold chest being reset on death
  keepondeath: true
  enabled: true

# Money Chest [uses Vault]
mchest:
  icon: emerald_block
  access: 10
  removelevel: false
  lockout: 300
  size: 27
  enabled: false

# Random Chest
rchest:
  icon: sponge
  access: 5
  removelevel: true
  lockout: 300
# timer - How long a player can stay in the chest before it closes
  timer: 15
  size: 54
  enabled: true

# Shuffle Chest
schest:
  icon: jack_o_lantern
  access: 2
  removelevel: true
  lockout: 120
# timer - How fast the chest shuffles, in seconds (uses double).
  timer: 0.5
  size: 54
  enabled: true

# Vault Chest
vchest:
  icon: ender_chest
  access: 5
  removelevel: true
  lockout: 0
# upgradelevel - How much XP levels a player requires to get a new slot row
  upgradelevel: 25
  enabled: true

# Swap Chest
wchest:
  icon: glass
  access: 2
  removelevel: false
  lockout: 120
  size: 27
  enabled: true

# Experience Chest
xchest:
  icon: sea_lantern
  access: 10
  removelevel: false
  lockout: 300
  size: 27
  enabled: true